// Generated by CoffeeScript 1.9.1
HTMLWidgets.widget({
  name: "iplotScantwo",
  type: "output",
  initialize: function(widgetdiv, width, height) {
    return d3.select(widgetdiv).append("svg").attr("class", "qtlcharts");
  },
  renderValue: function(widgetdiv, x) {
    return iplotScantwo(widgetdiv, x.scantwo_data, x.phenogeno_data, x.chartOpts);
  },
  resize: function(widgetdiv, width, height) {
    return null;
  }
});
