// Generated by CoffeeScript 1.7.1
var iplotScanone_noeff;

iplotScanone_noeff = function(data, chartOpts) {
  var axispos, chartdivid, chrGap, darkrect, halfh, height, lightrect, linecolor, linewidth, margin, mylodchart, nyticks, pointcolor, pointsize, rotate_ylab, title, titlepos, totalh, totalw, width, xlab, ylab, ylim, yticks, _ref, _ref1, _ref10, _ref11, _ref12, _ref13, _ref14, _ref15, _ref16, _ref17, _ref18, _ref19, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7, _ref8, _ref9;
  height = (_ref = chartOpts != null ? chartOpts.height : void 0) != null ? _ref : 450;
  width = (_ref1 = chartOpts != null ? chartOpts.width : void 0) != null ? _ref1 : 900;
  margin = (_ref2 = chartOpts != null ? chartOpts.margin : void 0) != null ? _ref2 : {
    left: 60,
    top: 40,
    right: 40,
    bottom: 40,
    inner: 5
  };
  axispos = (_ref3 = chartOpts != null ? chartOpts.axispos : void 0) != null ? _ref3 : {
    xtitle: 25,
    ytitle: 30,
    xlabel: 5,
    ylabel: 5
  };
  titlepos = (_ref4 = chartOpts != null ? chartOpts.titlepos : void 0) != null ? _ref4 : 20;
  ylim = (_ref5 = chartOpts != null ? chartOpts.ylim : void 0) != null ? _ref5 : null;
  nyticks = (_ref6 = chartOpts != null ? chartOpts.nyticks : void 0) != null ? _ref6 : 5;
  yticks = (_ref7 = chartOpts != null ? chartOpts.yticks : void 0) != null ? _ref7 : null;
  chrGap = (_ref8 = chartOpts != null ? chartOpts.chrGap : void 0) != null ? _ref8 : 8;
  darkrect = (_ref9 = chartOpts != null ? chartOpts.darkrect : void 0) != null ? _ref9 : d3.rgb(200, 200, 200);
  lightrect = (_ref10 = chartOpts != null ? chartOpts.lightrect : void 0) != null ? _ref10 : d3.rgb(230, 230, 230);
  linecolor = (_ref11 = chartOpts != null ? chartOpts.linecolor : void 0) != null ? _ref11 : "darkslateblue";
  linewidth = (_ref12 = chartOpts != null ? chartOpts.linewidth : void 0) != null ? _ref12 : 2;
  pointcolor = (_ref13 = chartOpts != null ? chartOpts.pointcolor : void 0) != null ? _ref13 : "#E9CFEC";
  pointsize = (_ref14 = chartOpts != null ? chartOpts.pointsize : void 0) != null ? _ref14 : 0;
  title = (_ref15 = chartOpts != null ? chartOpts.title : void 0) != null ? _ref15 : "";
  xlab = (_ref16 = chartOpts != null ? chartOpts.xlab : void 0) != null ? _ref16 : "Chromosome";
  ylab = (_ref17 = chartOpts != null ? chartOpts.ylab : void 0) != null ? _ref17 : "LOD score";
  rotate_ylab = (_ref18 = chartOpts != null ? chartOpts.rotate_ylab : void 0) != null ? _ref18 : null;
  chartdivid = (_ref19 = chartOpts != null ? chartOpts.chartdivid : void 0) != null ? _ref19 : 'chart';
  halfh = height + margin.top + margin.bottom;
  totalh = halfh * 2;
  totalw = width + margin.left + margin.right;
  mylodchart = lodchart().lodvarname("lod").height(height).width(width).margin(margin).axispos(axispos).titlepos(titlepos).ylim(ylim).nyticks(nyticks).yticks(yticks).chrGap(chrGap).darkrect(darkrect).lightrect(lightrect).linecolor(linecolor).linewidth(linewidth).pointcolor(pointcolor).pointsize(pointsize).title(title).xlab(xlab).ylab(ylab).rotate_ylab(rotate_ylab);
  d3.select("div#" + chartdivid).datum(data).call(mylodchart);
  return mylodchart.markerSelect().on("click", function(d) {
    var r;
    r = d3.select(this).attr("r");
    return d3.select(this).transition().duration(500).attr("r", r * 3).transition().duration(500).attr("r", r);
  });
};
