// Generated by CoffeeScript 1.7.1
var iplotScanone_noeff;

iplotScanone_noeff = function(data, chartOpts) {
  var chartdivid, halfh, height, margin, mylodchart, totalh, totalw, width, _ref, _ref1, _ref2, _ref3;
  height = (_ref = chartOpts != null ? chartOpts.height : void 0) != null ? _ref : 450;
  width = (_ref1 = chartOpts != null ? chartOpts.width : void 0) != null ? _ref1 : 900;
  margin = (_ref2 = chartOpts != null ? chartOpts.margin : void 0) != null ? _ref2 : {
    left: 60,
    top: 40,
    right: 40,
    bottom: 40,
    inner: 5
  };
  chartdivid = (_ref3 = chartOpts != null ? chartOpts.chartdivid : void 0) != null ? _ref3 : 'chart';
  halfh = height + margin.top + margin.bottom;
  totalh = halfh * 2;
  totalw = width + margin.left + margin.right;
  mylodchart = lodchart().lodvarname("lod").height(height).width(width).margin(margin);
  d3.select("div#" + chartdivid).datum(data).call(mylodchart);
  return mylodchart.markerSelect().on("click", function(d) {
    var r;
    r = d3.select(this).attr("r");
    return d3.select(this).transition().duration(500).attr("r", r * 3).transition().duration(500).attr("r", r);
  });
};
