// Generated by CoffeeScript 1.6.3
var iplotPXG;

iplotPXG = function(data) {
  var gen, gnames, h, inferred, margin, mychart, phe, w, x, y, _i, _ref, _results;
  gen = (function() {
    var _i, _len, _ref, _results;
    _ref = data.geno[0];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      x = _ref[_i];
      _results.push(Math.abs(x));
    }
    return _results;
  })();
  inferred = (function() {
    var _i, _len, _ref, _results;
    _ref = data.geno[0];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      x = _ref[_i];
      _results.push(x < 0);
    }
    return _results;
  })();
  phe = data.pheno;
  gnames = ((function() {
    var _results;
    _results = [];
    for (y in data.genonames) {
      _results.push(data.genonames[y]);
    }
    return _results;
  })())[0];
  h = 450;
  w = 900;
  margin = {
    left: 60,
    top: 40,
    right: 40,
    bottom: 40,
    inner: 5
  };
  mychart = dotchart().height(h).width(w).margin(margin).xcategories((function() {
    _results = [];
    for (var _i = 1, _ref = gnames.length; 1 <= _ref ? _i <= _ref : _i >= _ref; 1 <= _ref ? _i++ : _i--){ _results.push(_i); }
    return _results;
  }).apply(this)).xcatlabels(gnames).dataByInd(false);
  d3.select("div#chart").datum([gen, phe]).call(mychart);
  return mychart.pointsSelect().attr("fill", function(d, i) {
    if (inferred[i]) {
      return "Orchid";
    }
    return "slateblue";
  }).on("click", function(d) {
    var r;
    r = d3.select(this).attr("r");
    return d3.select(this).transition().duration(500).attr("r", r * 3).transition().duration(500).attr("r", r);
  });
};
