// Generated by CoffeeScript 1.7.1
var selectedMarker;

selectedMarker = "";

$("#markerinput").submit(function() {
  var newSelection;
  newSelection = document.getElementById("marker").value;
  console.log("input: " + newSelection);
  event.preventDefault();
  if (newSelection !== "" && newSelection !== selectedMarker) {
    if (markernames.indexOf(newSelection) >= 0) {
      selectedMarker = newSelection;
      console.log("selected marker: " + selectedMarker);
      d3.select("a#currentmarker").text(selectedMarker);
      return true;
    } else {
      d3.select("a#currentmarker").text("Marker \"" + selectedMarker + "\" not found");
    }
  }
  return false;
});

$('input#marker').autocomplete({
  autoFocus: true,
  source: function(request, response) {
    var matches;
    matches = $.map(markernames, function(tag) {
      if (tag.toUpperCase().indexOf(request.term.toUpperCase()) === 0) {
        return tag;
      }
    });
    return response(matches);
  },
  select: function(event, ui) {
    $('input#marker').val(ui.item.label);
    return $('input#submit').submit();
  }
});

$('input#marker').each(function() {
  return $(this).data('default', $(this).val()).addClass('inactive').focus(function() {
    $(this).removeClass('inactive');
    if ($(this).val() === $(this).data('default') || $(this).val() === '') {
      return $(this).val('');
    }
  }).blur(function() {
    if ($(this).val() === '') {
      return $(this).addClass('inactive').val($(this).data('default'));
    }
  });
});
