%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{R/qtlcharts Developer Guide}

# R/qtlcharts Developer Guide

[R/qtlcharts](http://kbroman.github.io/qtlcharts) is an
[R](http://www.r-project.org) package to create interactive charts for
QTL data, for use with [R/qtl](http://www.rqtl.org).
R/qtlcharts is written in
[R](http://www.r-project.org) and
[CoffeeScript](http://coffeescript.org), making use of the JavaScript
libraries [D3](http://d3js.org) and
[d3-tip](https://github.com/caged/d3-tip), as well as
[ColorBrewer](http://colorbrewer2.org).

The aim of this guide is to explain the basic strategy of the package
and the organization of the code, in the hope that others may wish to
contribute to its development or to make use of different pieces of
the software.

## Basic layout of source

The source for the package is at
[GitHub](http://github.com/kbroman/qtlcharts):
[`http://github.com/kbroman/qtlcharts`](http://github.com/kbroman/qtlcharts).
The [`devel` branch](https://github.com/kbroman/qtlcharts/tree/devel)
contains the current development version, but it is not far ahead (if
at all) from the
[`master` branch](https://github.com/kbroman/qtlcharts/tree/master).

JavaScript and CoffeeScript code are within the
[`inst/`](https://github.com/kbroman/qtlcharts/tree/master/inst)
subdirectory. (When the package is _installed_, the contents of the
`inst` directory are moved up one level, and there is no `inst`
directory anymore.)

The three main libraries are in
[`inst/d3`](https://github.com/kbroman/qtlcharts/tree/master/inst/d3),
[`inst/d3-tip`](https://github.com/kbroman/qtlcharts/tree/master/inst/d3-tip)
and
[`inst/colorbrewer`](https://github.com/kbroman/qtlcharts/tree/master/inst/colorbrewer).

The interactive charts are built on a set of
[reuseable D3-based graphic panels](http://kbroman.github.io/qtlcharts/pages/panels.html),
contained in
[`inst/panels`](https://github.com/kbroman/qtlcharts/tree/master/inst/panels).
These were designed following
[Mike Bostock](http://bost.ocks.org/mike)'s
[Towards Reuseable Charts](http://bost.ocks.org/mike/chart/).
[`panelutil.coffee`](https://github.com/kbroman/qtlcharts/tree/master/inst/panels/panelutil.coffee)
contains various utility functions used by one or more panels, and
[`panelutil.css`](https://github.com/kbroman/qtlcharts/tree/master/inst/panels/panelutil.css)
contains CSS code for the panels. The actual panels are in
subdirectories of
[`inst/panels`](https://github.com/kbroman/qtlcharts/tree/master/inst/panels),
and each contains a `test` subdirectory with test code.

The higher-level charts are located in
[`inst/charts`](https://github.com/kbroman/qtlcharts/tree/master/inst/charts).
This is where most of the interactivity is encoded: a chart basically
passes data to individual panels and sets up the interactions among
the panels.
[`charts.css`](https://github.com/kbroman/qtlcharts/blob/master/inst/charts/charts.css)
contains a bit of CSS code for the charts.


## CoffeeScript

R/qtlcharts is being developed in
[CoffeeScript](http://coffeescript.org) rather than JavaScript,
though the CoffeeScript code is translated to JavaScript and it is
the JavaScript that is ultimately used.

The CoffeeScript code is not that far from JavaScript: the bulk of the
code is basically not different. So why add this extra layer, with
CoffeeScript? CoffeeScript is a nicer language
and is more fun to code, and a number of things are easier or more
compact than JavaScript.

For example, [D3](http://d3js.org) code generally includes a lot of anonymous
functions, like

    blah.attr("x", function(d) { return xscale(d); });

In CoffeeScript, this becomes

    blah.attr("x", (d) -> xscale(d))

Also, in dealing with missing values, or with default values,
CoffeeScript has some features that make life easier. Here's an
example:

    height = chartOpts?.height ? 450

The JavaScript version of this is cumbersome and ugly.


## Basic strategy

For each chart there is an R function that writes to an html file (by
default, a temporary file in a temporary directory, defined with
[`tempfile()`](http://stat.ethz.ch/R-manual/R-devel/library/base/html/tempfile.html)
and
[`tempdir()`](http://stat.ethz.ch/R-manual/R-devel/library/base/html/tempfile.html)),
which is then opened in a browser.

The data are simply pasted into the html file in
[JSON](http://json.org) format. This may make the chart slow to load,
but it allows us to get around browser security settings which
generally disallow access to local files.

The basic functions for writing html are in
[`write_html.R`](https://github.com/kbroman/qtlcharts/blob/master/R/write_html.R).
The R function [`system.file`](http://stat.ethz.ch/R-manual/R-devel/library/base/html/system.file.html) is used to define links to the JavaScript
and CSS code that are contained within the package. For example, the
location of the `d3.min.js` file is determined through

    system.file('d3', 'd3.min.js', package='qtlcharts')

We're generally using temporary files and writing links to the
JavaScript code, but if the argument `onefile=TRUE`, we paste the code
directly using the R function
[`file.append`](http://stat.ethz.ch/R-manual/R-patched/library/base/html/files.html). (The
resulting file is then self-contained and so portable.)

For creating interactive charts within R Markdown documents (see
[the related vignette](http://kbroman.github.io/qtlcharts/assets/vignettes/Rmarkdown.html)),
one would use `print=TRUE`, in which case rather than appending code
to a file, we'd simply print it (with `cat(readLines(file), sep="\n")`).

Customization options for a chart are passed via an R argument
`chartOpts`, which is also written to the html file in JSON format and
passed as an argument to the relevant chart function. The chart itself
will be placed within a `<div>` with an ID specific to the chart (by
default, `chart`. The names of the data objects (including the
`chartOpts` object) are prepended with this same div ID. This is to
avoid conflicts among multiple charts, particularly within
[R Markdown files](http://kbroman.github.io/qtlcharts/assets/vignettes/Rmarkdown.html).

## Customization options

For each chart, there are numerous possible customizations that one
may wish to apply. To simplify the maintenance of these options, the R
function for each chart takes an argument `chartOpts`, that is a named
list (in simple cases, a named vector will do). This is passed to the
corresponding CoffeeScript function for the chart, which looks for
specific named components. If a specific option (e.g., `height` or
`width`) is named, the option is used in place of the default.

The allowable options are maintained in one place: the CoffeeScript
code in which they are used. These need to be listed at the top of the
file in a format like the following (taken from
[`iplotCorr.coffee`](https://github.com/kbroman/qtlcharts/tree/master/inst/charts/iplotCorr.coffee)).

    # chartOpts start
    height = chartOpts?.height ? 450 # height of each panel in pixels
    width = chartOpts?.width ? height # width of each panel in pixels
    margin = chartOpts?.margin ? {left:70, top:40, right:5, bottom: 70, inner:5} # margins in pixels (left, top, right, bottom, inner)
    corcolors = chartOpts?.corcolors ? ["darkslateblue", "white", "crimson"] # heat map colors (same length as `zlim`)
    zlim = chartOpts?.zlim ? [-1, 0, 1] # z-axis limits
    rectcolor = chartOpts?.rectcolor ? "#E6E6E6" # color of background rectangle
    cortitle = chartOpts?.cortitle ? "" # title for heatmap panel
    scattitle = chartOpts?.scattitle ? "" # title for scatterplot panel
    scatcolors = chartOpts?.scatcolors ? null # vector of point colors for scatterplot
    # chartOpts end

The name of the option used within the file (on the left) should match
that used within the R code (e.g., `height` and `chartOpts.height`),
and each line should end with a comment describing the option.
This is so that a ruby script
([`grab_chartOpts.rb`](https://github.com/kbroman/qtlcharts/blob/master/vignettes/chartOpts/grab_chartOpts.rb))
can parse all of these options and create the
[chartOpts vignette](http://kbroman.github.io/qtlcharts/assets/vignettes/chartOpts.html),
which provides a list of all possible options.

Some charts have multiple versions (e.g., `iplotScanone` with no
effects, with confidence intervals, or with raw phenotype &times;
genotype).  The file [`multiversions.csv`](https://github.com/kbroman/qtlcharts/blob/master/vignettes/chartOpts/multiversions.csv)
lists the chart name and a bit of Markdown code to describe the
version. Also, the order of the charts in the
[chartOpts vignette](http://kbroman.github.io/qtlcharts/assets/vignettes/chartOpts.html)
is determined from the order in this file.



## R &rarr; JSON

Data is pasted into the chart file as [JSON](http://json.org); they are converted from R
objects to JSON using the
[jsonlite](https://github.com/jeroenooms/jsonlite) package.

There are some occasional annoyances, particularly in ensuring that
an object becomes a hash (i.e., associative array) or an array (i.e.,
vector or list), or that a single value becomes a scalar or an array
of length 1.

Things that are to be converted to hashes should first be made into
lists, as regular vectors in R will be converted to ordered arrays,
with any `names` ignored.

The other bit of trickiness regards vectors of length 1. R does not
have a scalar data type; one uses a vector of length 1. But in JSON
and JavaScript, these are different, and it can be annoying to deal
with a vector of length 1 where a scalar would do. The function
`jsonlite::unbox` can be used to force a vector of length 1 to be made
a scalar.

We mess around with these things particularly in dealing with the
`chartOpts` options. The function `opts4json` (see
[`write_html.R`](https://github.com/kbroman/qtlcharts/blob/master/R/write_html.R))
is the main utility for ensuring that `chartOpts` get turned into the
expected JSON format.

A further annoyance regards the treatment of missing values: in some
cases jsonlite will convert missing values to `"NA"` strings, and in
some cases will be made `null` values. Use of `na="null"` in calls to
`jsonlite::toJSON` will force the use of `null` values.

An additional difficulty with jsonlite concerns the number of digits that are
retained in the JSON object. jsonlite is currently using `round` (see
[`asJSON.numeric.R`](https://github.com/jeroenooms/jsonlite/blob/master/R/asJSON.numeric.R)),
though `formatC` would probably be better.
Most chart functions in R/qtlcharts take a `digits` argument which is
passed to the `toJSON` to control the number of digits retained in the
JSON objects. We want sufficient digits to keep things from looking
too discrete in the chart, but too many digits results in large files
and load times.

Originally, jsonlite produced JSON objects with a great deal of white
space, and so R/qtlcharts contains a function `strip_whitespace` (see
[`write_html.R`](https://github.com/kbroman/qtlcharts/blob/master/R/write_html.R)),
but it's a bit tricky to deal with strings with nested quotes.  In the
most recent version of jsonlite, this seems to no longer be an issue,
and so `strip_whitespace` could probably be omitted from R/qtlcharts.


## Roxygen

Using Roxygen to create R help files


## Tests

tricky to automatically test graphics, and particularly interactive
graphics

mention `tests/` and `inst/tests/` and the testthat package.



## Licenses

Licensed under the
[MIT license](LICENSE). ([More information here](http://en.wikipedia.org/wiki/MIT_License).)

R/qtlcharts incorporates [D3.js](http://d3js.org)
([see its license](https://github.com/kbroman/qtlcharts/blob/master/inst/d3/LICENSE)),
[d3.tip](http://github.com/Caged/d3-tip)
([see its license](https://github.com/kbroman/qtlcharts/blob/master/inst/d3-tip/LICENSE)),
and [ColorBrewer](http://colorbrewer2.org)
([see its license](https://github.com/kbroman/qtlcharts/blob/master/inst/colorbrewer/LICENSE)).


<!-- the following to make it look nicer -->
<link href="http://kbroman.github.io/qtlcharts/assets/vignettes/vignette.css" rel="stylesheet"></link>
