// Generated by CoffeeScript 1.10.0
var itriplot;

itriplot = function(widgetdiv, data, chartOpts) {
  var boxcolor, boxwidth, chartdivid, height, labelpos, labels, margin, mychart, pointcolor, pointsize, pointstroke, rectcolor, ref, ref1, ref10, ref11, ref12, ref13, ref14, ref2, ref3, ref4, ref5, ref6, ref7, ref8, ref9, tipclass, title, titlepos, widgetdivid, width;
  width = (ref = chartOpts != null ? chartOpts.width : void 0) != null ? ref : 600;
  height = (ref1 = chartOpts != null ? chartOpts.height : void 0) != null ? ref1 : 520;
  margin = (ref2 = chartOpts != null ? chartOpts.margin : void 0) != null ? ref2 : {
    left: 60,
    top: 40,
    right: 60,
    bottom: 10
  };
  labelpos = (ref3 = chartOpts != null ? chartOpts.labelpos : void 0) != null ? ref3 : 10;
  titlepos = (ref4 = chartOpts != null ? chartOpts.titlepos : void 0) != null ? ref4 : 20;
  title = (ref5 = chartOpts != null ? chartOpts.title : void 0) != null ? ref5 : "";
  labels = (ref6 = chartOpts != null ? chartOpts.labels : void 0) != null ? ref6 : ["(1,0,0)", "(0,1,0)", "(0,0,1)"];
  rectcolor = (ref7 = chartOpts != null ? chartOpts.rectcolor : void 0) != null ? ref7 : "#e6e6e6";
  boxcolor = (ref8 = chartOpts != null ? chartOpts.boxcolor : void 0) != null ? ref8 : "black";
  boxwidth = (ref9 = chartOpts != null ? chartOpts.boxwidth : void 0) != null ? ref9 : 2;
  pointcolor = (ref10 = chartOpts != null ? chartOpts.pointcolor : void 0) != null ? ref10 : null;
  pointstroke = (ref11 = chartOpts != null ? chartOpts.pointstroke : void 0) != null ? ref11 : "black";
  pointsize = (ref12 = chartOpts != null ? chartOpts.pointsize : void 0) != null ? ref12 : 3;
  tipclass = (ref13 = chartOpts != null ? chartOpts.tipclass : void 0) != null ? ref13 : "tooltip";
  chartdivid = (ref14 = chartOpts != null ? chartOpts.chartdivid : void 0) != null ? ref14 : 'chart';
  widgetdivid = d3.select(widgetdiv).attr('id');
  mychart = d3panels.trichart({
    height: height,
    width: width,
    margin: margin,
    labelpos: labelpos,
    titlepos: titlepos,
    title: title,
    labels: labels,
    rectcolor: rectcolor,
    boxcolor: boxcolor,
    boxwidth: boxwidth,
    pointcolor: pointcolor,
    pointsize: pointsize,
    pointstroke: pointstroke,
    tipclass: widgetdivid
  });
  mychart(d3.select(widgetdiv).select("svg"), data);
  return mychart.points().on("mouseover", function(d) {
    return d3.select(this).attr("r", pointsize * 2);
  }).on("mouseout", function(d) {
    return d3.select(this).attr("r", pointsize);
  });
};
